# Site settings
title: "Haru's resume page"
description: "A resume for Haru Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Haruhiko Takeuchi"
resume_title:                   "Researcher (~2021)" # 役職

# used for the contact button in _layouts/resume.html
resume_contact_email:           "takeuchi.haruhiko@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "090-6335-4043"
resume_contact_address:         "1-1 yanagido Gifu, Gifu"

resume_header_contact_info:     "1-1 yanagido Gifu, Gifu • 501-1193 • takeuchi.haruhiko@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>I'm Haruhiko, a 2nd year of master's program at Gifu University, and I'm called Haru. I am researching millimeter waves used for autonomous driving, and have recently applied it to machine learning. I'm not only a Software Engineer but also a 3D modeler. To work as SIer from April 2021.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
#resume_section_projects:        true
resume_section_skills:          true
#resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/h4r3"
  resume_twitter_url:           "http://twitter.com/_h4r3"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://jp.linkedin.com/in/haruhiko-takeuchi-5348721bb/ja-jp?trk=people-guest_people_search-card&challengeId=AQFNx4kV2nZpSwAAAXaovMEVHKpIE7OiMI9XhNErv6u78OELOnrZ68TpXtKz7Wx7Bm7dNkKT_I7QZQAHQbWna1I7oQSwhmwRvw&submissionId=99827d1c-3ad8-5416-7684-19621f70864cr"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
